### ISSUE TITLE
Many items added?(많은 아이템이 추가되었나요?)

### ISSUE THREAD

**Issue by shdudwns** [FrontierDevs/FrontierEdge#2]
Can I recall many items and all monsters? You can get it from the driver named TSP
(많은 아이템과 모든 몬스터를 소환이 가능한가요? TSP라는 구동기에서 가져올수 있습니다)

**Comment by xXSirGamesXx** [comment]
Not sure what you mean. Can you elaborate

**Comment by shdudwns** [comment]
@xXSirGAMESXx
Did you add a lot of items once?

**Comment by xXSirGamesXx** [comment]
We will be adding hopefully most of the items
